# Site settings
title: Enzyklopädie eines Entwicklers (E3)
email: posixpascal@googlemail.com
description: >
  Mein persönliches Nachschlagewerk. Kurze und präzise Anleitungen, Tipps, Diskussionen und
  einiges Mehr über Technik, Programmierung und Prognosen.
baseurl: "http://localhost:8000"
url: "http://pascalraszyk.de" # the base hostname & protocol for your site
twitter_username: ninetyfourJS
github_username:  posixpascal
timezone: Europe/Berlin
# Build settings
markdown: kramdown
