# Site settings
title: meh.
email: posixpascal@googlemail.com
description: >
  Hier entstehen, lasst mich nicht lügen, 3 Beiträge im Jahr, viel Spaß.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pascalraszyk.de" # the base hostname & protocol for your site
twitter_username: pascalraszyk
github_username:  posixpascal

# Build settings
markdown: kramdown
